"""create_transfers_table

Revision ID: 4f560cbb3d1f
Revises: 
Create Date: 2025-02-16 22:08:43.072174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f560cbb3d1f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at_date', sa.Date(), nullable=False),
    sa.Column('created_at_time', sa.Time(), nullable=False),
    sa.Column('transfer_id', sa.String(), nullable=False),
    sa.Column('date_to_local', sa.Date(), nullable=True),
    sa.Column('time_to_local', sa.Time(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('from_location', sa.String(), nullable=True),
    sa.Column('to_location', sa.String(), nullable=True),
    sa.Column('pax', sa.Integer(), nullable=True),
    sa.Column('transport_type_ids', sa.String(), nullable=True),
    sa.Column('carrier_offer_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfers_id'), 'transfers', ['id'], unique=False)
    op.create_index(op.f('ix_transfers_transfer_id'), 'transfers', ['transfer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfers_transfer_id'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_id'), table_name='transfers')
    op.drop_table('transfers')
    # ### end Alembic commands ###
