"""Add is_read, is_reply, and reply_to to TelegramMessage

Revision ID: 3213166fa02d
Revises: 433e0f330f9b
Create Date: 2025-01-26 20:20:58.091086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3213166fa02d'
down_revision: Union[str, None] = '433e0f330f9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_messages', sa.Column('is_read', sa.Boolean(), nullable=True))
    op.add_column('telegram_messages', sa.Column('is_reply', sa.Boolean(), nullable=True))
    op.add_column('telegram_messages', sa.Column('reply_to', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'telegram_messages', 'telegram_messages', ['reply_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'telegram_messages', type_='foreignkey')
    op.drop_column('telegram_messages', 'reply_to')
    op.drop_column('telegram_messages', 'is_reply')
    op.drop_column('telegram_messages', 'is_read')
    # ### end Alembic commands ###
