"""Create telegram_messages table

Revision ID: 4446e88af709
Revises: 84cc3a9af94c
Create Date: 2025-01-24 12:52:30.217838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4446e88af709'
down_revision: Union[str, None] = '84cc3a9af94c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('sender_username', sa.String(length=255), nullable=True),
    sa.Column('sender_id', sa.BigInteger(), nullable=True),
    sa.Column('sender_phone', sa.String(length=20), nullable=True),
    sa.Column('sender_type', sa.String(length=50), nullable=True),
    sa.Column('recipient_name', sa.String(length=255), nullable=True),
    sa.Column('recipient_username', sa.String(length=255), nullable=True),
    sa.Column('recipient_id', sa.BigInteger(), nullable=True),
    sa.Column('recipient_phone', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telegram_messages')
    # ### end Alembic commands ###
