"""Add chat_id, direction to TelegramMessage

Revision ID: 97840eacc277
Revises: 3213166fa02d
Create Date: 2025-01-27 10:33:15.210833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97840eacc277'
down_revision: Union[str, None] = '3213166fa02d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_messages', sa.Column('chat_id', sa.Integer(), nullable=True))
    op.add_column('telegram_messages', sa.Column('direction', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_messages', 'direction')
    op.drop_column('telegram_messages', 'chat_id')
    # ### end Alembic commands ###
