"""Sync existing tables and add new migrations

Revision ID: b220bc9324d3
Revises: d75c90d6a6ae
Create Date: 2025-01-25 16:29:07.011445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b220bc9324d3'
down_revision: Union[str, None] = 'd75c90d6a6ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contacts_contact_type', table_name='contacts', mysql_length={'contact_type': 191})
    op.drop_index('ix_contacts_username', table_name='contacts', mysql_length={'username': 191})
    op.alter_column('telegram_messages', 'sender_id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('telegram_messages', 'recipient_id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('telegram_messages', 'message',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.create_foreign_key(None, 'telegram_messages', 'telegram_senders', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'telegram_messages', 'telegram_recipients', ['recipient_id'], ['id'])
    op.drop_column('telegram_messages', 'recipient_phone')
    op.drop_column('telegram_messages', 'sender_username')
    op.drop_column('telegram_messages', 'sender_name')
    op.drop_column('telegram_messages', 'sender_phone')
    op.drop_column('telegram_messages', 'recipient_name')
    op.drop_column('telegram_messages', 'recipient_username')
    op.drop_column('telegram_messages', 'sender_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_messages', sa.Column('sender_type', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('telegram_messages', sa.Column('recipient_username', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('telegram_messages', sa.Column('recipient_name', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('telegram_messages', sa.Column('sender_phone', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('telegram_messages', sa.Column('sender_name', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('telegram_messages', sa.Column('sender_username', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('telegram_messages', sa.Column('recipient_phone', mysql.VARCHAR(length=20), nullable=True))
    op.drop_constraint(None, 'telegram_messages', type_='foreignkey')
    op.drop_constraint(None, 'telegram_messages', type_='foreignkey')
    op.alter_column('telegram_messages', 'message',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('telegram_messages', 'recipient_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               nullable=True)
    op.alter_column('telegram_messages', 'sender_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               nullable=True)
    op.create_index('ix_contacts_username', 'contacts', ['username'], unique=False, mysql_length={'username': 191})
    op.create_index('ix_contacts_contact_type', 'contacts', ['contact_type'], unique=False, mysql_length={'contact_type': 191})
    # ### end Alembic commands ###
