services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    volumes:
      - ./client/temp:/client/temp
      - ./client/log:/client/log
    env_file:
      - ./.env
    environment:
      - TZ=${TIMEZONE}
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge