services:
  nodriver-auth:
    image: dorowu/ubuntu-desktop-lxde-vnc:latest
    container_name: nodriver-manual-auth
    ports:
      - "6080:80"
      - "5900:5900"
    volumes:
      - ./app:/workspace/app
      - ./cookies:/home/ubuntu/tikleap_work/cookies
      - ./data:/workspace/data
    environment:
      - VNC_PASSWORD=secret
      - RESOLUTION=1366x768
    
    mem_limit: 1g
    cpus: '1.0'
    shm_size: 512mb
    restart: "no"
    
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
