FROM python:3.12-slim

WORKDIR /api

RUN apt-get update && apt-get install -y openssl curl

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "tracking_runner.py"]