"""Add order_status table

Revision ID: 9fd41b4ff93a
Revises: 
Create Date: 2025-03-08 17:13:30.087707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fd41b4ff93a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_source_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('parameter', sa.String(length=50), nullable=True),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('name_translate', sa.String(length=255), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('document_name', sa.String(length=255), nullable=True),
    sa.Column('default_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('mass', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('volume', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('length', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('width', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('height', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rest_count', sa.Integer(), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('cost_price_currency_id', sa.Integer(), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('uktzed', sa.String(length=50), nullable=True),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('percent_discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_period_from', sa.Date(), nullable=True),
    sa.Column('discount_period_to', sa.Date(), nullable=True),
    sa.Column('is_complect', sa.Boolean(), nullable=True),
    sa.Column('product_group', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.create_table('shipping_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tip_prodaju_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact',
    sa.Column('form_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('con_ugc', sa.Text(), nullable=True),
    sa.Column('con_bloger', sa.Text(), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('con_povnaoplata', sa.Text(), nullable=True),
    sa.Column('counterparty_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('leads_count', sa.Integer(), nullable=True),
    sa.Column('leads_sales_count', sa.Integer(), nullable=True),
    sa.Column('leads_sales_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['manager.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_id'), 'contact', ['id'], unique=False)
    op.create_table('order',
    sa.Column('form_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('shipping_method_id', sa.Integer(), nullable=True),
    sa.Column('shipping_method_text', sa.String(length=100), nullable=True),
    sa.Column('payment_method_id', sa.Integer(), nullable=True),
    sa.Column('payment_method_text', sa.String(length=100), nullable=True),
    sa.Column('shipping_address', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('time_entry_order', sa.Time(), nullable=True),
    sa.Column('holder_time', sa.DateTime(), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('order_time', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('status_text', sa.String(length=100), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('payment_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('commission_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cost_price_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('shipping_costs', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expenses_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('type_text', sa.String(length=100), nullable=True),
    sa.Column('payed_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rest_pay', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('call', sa.Boolean(), nullable=True),
    sa.Column('sajt', sa.String(length=100), nullable=True),
    sa.Column('external_id', sa.String(length=50), nullable=True),
    sa.Column('utm_page', sa.Text(), nullable=True),
    sa.Column('utm_medium', sa.String(length=100), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('campaign_name', sa.String(length=100), nullable=True),
    sa.Column('utm_source_full', sa.Text(), nullable=True),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.Column('utm_content', sa.String(length=100), nullable=True),
    sa.Column('utm_term', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_method.id'], ),
    sa.ForeignKeyConstraint(['shipping_method_id'], ['shipping_method.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['order_status.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['order_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['manager.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_id'), 'order', ['id'], unique=False)
    op.create_table('product_complect',
    sa.Column('form_id', sa.Integer(), nullable=True),
    sa.Column('complect_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['complect_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_complect_id'), 'product_complect', ['id'], unique=False)
    op.create_table('product_stock_balance',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'stock_id')
    )
    op.create_table('contact_email',
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('contact_id', 'email')
    )
    op.create_table('contact_phone',
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('contact_id', 'phone')
    )
    op.create_table('delivery_data',
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('city_name', sa.String(length=100), nullable=True),
    sa.Column('status_code', sa.String(length=50), nullable=True),
    sa.Column('delivery_date_and_time', sa.DateTime(), nullable=True),
    sa.Column('back_delivery', sa.Boolean(), nullable=True),
    sa.Column('pay_for_delivery', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_data_id'), 'delivery_data', ['id'], unique=False)
    op.create_table('nova_poshta_data',
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('id_entity', sa.Integer(), nullable=True),
    sa.Column('city_name', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('branch_number', sa.Integer(), nullable=True),
    sa.Column('warehouse_type_id', sa.Integer(), nullable=True),
    sa.Column('back_delivery_sum', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('manual', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nova_poshta_data_id'), 'nova_poshta_data', ['id'], unique=False)
    op.create_table('order_check',
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('fiscal_code', sa.String(length=50), nullable=True),
    sa.Column('fiscal_id', sa.String(length=50), nullable=True),
    sa.Column('fiscalization_status', sa.String(length=50), nullable=True),
    sa.Column('receipt_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_check_id'), 'order_check', ['id'], unique=False)
    op.create_table('order_client_source',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['client_source_type.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'source_id')
    )
    op.create_table('order_contact',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'contact_id')
    )
    op.create_table('order_product',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('product_category', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('percent_discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_with_discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sale_date', sa.Date(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('quarter', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month_year', sa.String(length=7), nullable=True),
    sa.Column('tip_prodazu', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'product_id')
    )
    op.create_table('order_sales_type',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('sales_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['sales_type_id'], ['tip_prodaju_type.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'sales_type_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_sales_type')
    op.drop_table('order_product')
    op.drop_table('order_contact')
    op.drop_table('order_client_source')
    op.drop_index(op.f('ix_order_check_id'), table_name='order_check')
    op.drop_table('order_check')
    op.drop_index(op.f('ix_nova_poshta_data_id'), table_name='nova_poshta_data')
    op.drop_table('nova_poshta_data')
    op.drop_index(op.f('ix_delivery_data_id'), table_name='delivery_data')
    op.drop_table('delivery_data')
    op.drop_table('contact_phone')
    op.drop_table('contact_email')
    op.drop_table('product_stock_balance')
    op.drop_index(op.f('ix_product_complect_id'), table_name='product_complect')
    op.drop_table('product_complect')
    op.drop_index(op.f('ix_order_id'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_contact_id'), table_name='contact')
    op.drop_table('contact')
    op.drop_table('tip_prodaju_type')
    op.drop_table('stock')
    op.drop_table('shipping_method')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_table('product')
    op.drop_table('payment_method')
    op.drop_table('organization')
    op.drop_table('order_type')
    op.drop_table('order_status')
    op.drop_table('manager')
    op.drop_table('client_source_type')
    op.drop_table('campaign')
    # ### end Alembic commands ###